/camera_driver:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 15.0
    resolution_width: 1280
    resolution_height: 1024
    offsetX: 0
    offsetY: 0
    camera_name: "daheng"

/video_player:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    path: "/home/zcf/csurm/csurm-RMUC2022/ood_red(1).mp4"
    frame_rate: 24
    start_frame: 0
    frame_id: "camera_optical_frame"

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    port_name: "/dev/ttyUART"
    protocol: "infantry"


/virtual_serial:
  ros__parameters:
    vision_mode: 0

/armor_detector:
  ros__parameters:
    debug: true
    detect_color: 0
    binary_thres: 120

    light.min_ratio: 0.1
    light.color_diff_thresh: 25
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_solver:
  ros__parameters:
    debug: true
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0
    
    solver:
      bullet_speed: 25.0
      gravity: 10.0
      time_offset: 0.0
